// Canonical entry-point body: the single source of truth for every harness bootstrap
// (CLAUDE.md, BASE_BOOTSTRAP.md, .cursor/rules/assistant.mdc, AGENTS.md and the tool
// matrix). Every consumer — `base build`, `base init`, the committed starters — calls THESE
// renderers; none carries a copy.
//
// The files are GENERATED by `base build` from the constants below and gated for freshness in CI,
// so they cannot drift. The policy is deliberately **agent-agnostic**: the entry point is a router, not
// an identity: it never hard-codes a default agent. Routing happens at task boundaries (or on `R`),
// through the deterministic engine (MCP tool first, CLI second), never by the LLM reading a catalogue.

import path from "node:path";
import { compareByCodePoint } from "./ordering.mjs";

export const ROUTER_INTRO =
  "Ce projet est un BASE: des agents et des process en texte. Tu n'as **pas d'identité fixe**; tu es le routeur.";

export const ROUTER_BODY = [
  "## Quand router",
  "- Quand l'utilisateur veut **accomplir une tâche** qui demande un process ou un savoir-faire précis (pas une simple discussion).",
  "- Quand le bon agent/process n'est **pas évident**.",
  "- Quand l'utilisateur écrit **«R»** (ou «R <demande>») pour forcer un routage.",
  "",
  "Cas directs (ne route pas): si l'utilisateur **nomme un agent** («charge l'assistant devis»), ouvre directement son `AGENT.md`. C'est le seul fichier à charger. Et reste dans l'agent déjà chargé: ne route pas à chaque message.",
  "",
  "## Comment router",
  "Ta **carte**, c'est l'index généré: si `.ai/routing/index.md` existe, lis-le pour t'orienter. Il liste les agents et, pour chacun, ses process avec «Quand l'utiliser» et «Éviter si». Descends racine → agent → process; retiens le process dont le «Quand l'utiliser» couvre la demande, en respectant «Éviter si». Si aucun ne la couvre, abstiens-toi: ne devine pas.",
  "",
  "Le routeur déterministe confirme ton choix et sert de repli (index absent, ou doute). S'il désigne un autre process que le tien, c'est un signal d'ambiguïté: relis les «Quand l'utiliser»/«Éviter si», et si le doute persiste, demande plutôt que de trancher seul. Par ordre de préférence:",
  "1. **Outil MCP `route_request`** (si disponible) → appelle-le, charge l'`AGENT.md` de l'agent retourné, puis le `SKILL.md` du process retourné, et suis ce process.",
  "2. **Sinon, la CLI** (si un terminal est disponible) → `node .ai/base.mjs route \"<demande>\" --root .` depuis la racine du BASE. Ce lanceur est créé par `base init`; il trouve le moteur tout seul (via `framework_dir` dans `base.config.json`), sans rien sur le PATH. Charge ensuite l'agent et le process retournés. **Le même routeur déterministe, sans MCP.**",
  "3. **Sinon** (ni MCP ni terminal) → explique simplement l'intérêt d'un routage déterministe et honnête, et aide l'utilisateur à l'activer en suivant le process `activer-routage` (sinon `mcp/README.md` et `docs/`).",
  "",
  "Le routeur peut **s'abstenir** (`out_of_scope`, `ambiguous`, `needs_clarification`): pose alors la question qu'il propose, **ne devine pas**. Route d'abord, charge ensuite; aucun agent n'est l'agent par défaut.",
  "",
  "Si une abstention contient un **`fallback`** (un agent → process d'aide), charge ce fallback au lieu de laisser l'utilisateur sans suite: c'est l'accueil/orientation, pas une fausse réponse. S'il n'y a pas de fallback, pose la question proposée ou explique simplement la limite.",
].join("\n");

const GENERATED =
  "<!-- Généré par `base build bootstrap --write`. Ne pas éditer à la main: le corps canonique est dans `tools/core/bootstrap.mjs`. -->";

export function renderClaudeMd() {
  return block([
    "# BASE: Bâtir des Assistants avec une Structure d'Expertise",
    GENERATED,
    `Ce fichier est le **point d'entrée pour Claude Code**. ${ROUTER_INTRO}`,
    ROUTER_BODY,
  ]);
}

export function renderBootstrapMd() {
  return block([
    "# BASE: bootstrap générique",
    GENERATED,
    `Point d'entrée générique pour un harness IA. ${ROUTER_INTRO}`,
    ROUTER_BODY,
  ]);
}

export function renderCursorRule() {
  return block([
    "---\ndescription: BASE: routeur d'agents et de process pour votre métier\nalwaysApply: true\n---",
    GENERATED,
    ROUTER_INTRO,
    ROUTER_BODY,
  ]);
}

// The head of AGENTS.md: the canonical body, ending at the catalogue heading. The generated agent list
// is appended by the build (AGENTS.md is both the AGENTS-family bootstrap and the agent catalogue).
export function renderAgentsHeader() {
  return block([
    "# Agents",
    GENERATED,
    ROUTER_INTRO,
    ROUTER_BODY,
    "## Catalogue des agents",
  ]);
}

function block(parts) {
  return parts.join("\n\n");
}

/** AGENTS.md: the canonical router head followed by the agent catalogue, one line per agent. */
export function renderAgentsMd(resources) {
  const agents = resources
    .filter((resource) => resource.type === "agent")
    .filter((resource) => {
      const normalized = resource.path.split(path.sep).join("/");
      return normalized.startsWith(".ai/agents/") && !normalized.includes("/_");
    })
    .sort((a, b) => compareByCodePoint(a.path, b.path));

  const lines = [renderAgentsHeader(), ""];
  if (agents.length === 0) {
    lines.push("_Aucun agent dans `.ai/agents/`._");
  } else {
    for (const agent of agents) {
      const normalized = agent.path.split(path.sep).join("/");
      // Clean agent name = its directory (".ai/agents/<name>/AGENT.md"), not the slugified path id.
      const name = normalized.split("/").slice(-2, -1)[0] || agent.id;
      lines.push(`- **${name}** - ${agent.description || agent.title} → \`${normalized}\``);
    }
  }
  lines.push("");
  return lines.join("\n");
}

export function renderToolMatrix() {
  return [
    "# Matrice des outils BASE",
    "",
    "<!-- Généré par `base build`. Déclaration honnête des garanties atteignables quand l'action passe vraiment par BASE. -->",
    "",
    "Niveaux: 0 non supporté · 1 advisory (guide/audit) · 2 médiation partielle · 3 strict (médié).",
    "",
    "Règle d'honnêteté: cette matrice indique le niveau maximal atteignable par garantie quand",
    "l'action passe vraiment par BASE (CLI, broker, MCP ou connector configuré). Une action qui",
    "contourne BASE reste au niveau natif du harness.",
    "",
    "| Garantie | claude-code | cursor | chatgpt (mcp) | générique |",
    "| --- | --- | --- | --- | --- |",
    "| Confinement des chemins (accès médié) | 3 | 3 | 3 | 1 |",
    "| Confirmation avant écriture (propose/commit) | 3¹ | 2 | 3¹ | 1 |",
    "| Exécution d'outil (dry-run + confirm) | 3¹ | 2 | 3¹ | 1 |",
    "| Découverte native des skills | 3 | 2 | 1 | 1 |",
    "| Hooks / garde-fous mécaniques | 3² | 2² | 0 | 0 |",
    "",
    "¹ Niveau 3 uniquement pour les actions routées par le broker BASE (`propose`/`commit`, `invoke`).",
    "Une écriture ou exécution qui contourne le broker reste advisory.",
    "² Niveau atteignable seulement si le harness est configuré pour router les actions concernées",
    "vers le broker ou un hook. BASE ne livre pas ces hooks pour tous les harnesses.",
    "",
  ].join("\n");
}
